---
defaults:
  updatinator_container: &updatinator_container
    working_directory: /updatinator

version: 2
jobs:
  publish_phar:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$CIRCLE_TAG
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/update-tool.phar

workflows:
  version: 2
  push:
    jobs:
      - publish_phar:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
