name: Test
on:
  pull_request:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: test-fixtures
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: updatinate-wp-db
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set PHP version
        uses: shivammathur/setup-php@1c8b931092191aa6384909135bb73949ac1528ce # v2
        with:
          php-version: '8.2'
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress
      - name: Unset GitHub Tokens
        shell: bash
        run: |
          unset GITHUB_TOKEN
          unset GH_TOKEN
      - name: Verify GitHub auth
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PANTHEON_UPSTREAM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.PANTHEON_UPSTREAM_AUTH_TOKEN }}
        run: |
          git config --global user.email "bot@getpantheon.com"
          git config --global user.name "Pantheon Automation"
          gh auth status
      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          wp --info
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.PANTHEON_UPSTREAM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.PANTHEON_UPSTREAM_AUTH_TOKEN }}
          DB_USER: root
          DB_NAME: updatinate-wp-db
        run: composer test
  send-dispatch:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
        with:
          token: ${{ secrets.PANTHEON_UPSTREAM_AUTH_TOKEN }}
          repository: pantheon-systems/update-tool
          event-type: tests-passed
          client-payload: '{"tag_name": "${{ github.ref_name }}"}'
